import{a as v,S as w,i as n}from"./assets/vendor-CsOP1TRZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const b="51458279-4e6b2a3cff5506a1c0eebb844",S="https://pixabay.com/api/";async function m(r,o){const e=new URLSearchParams({key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15});return(await v.get(`${S}?${e}`)).data}const y=document.querySelector(".gallery"),g=document.querySelector(".load-more"),c=document.querySelector(".loader"),P=new w(".gallery a");function p(r){const o=r.map(e=>`
      <li>
        <a class="gallery-item" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <div><span>Likes</span> ${e.likes}</div>
            <div><span>Views</span> ${e.views}</div>
            <div><span>Comments</span> ${e.comments}</div>
            <div><span>Downloads</span> ${e.downloads}</div>
          </div>
        </a>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),P.refresh()}function q(){y.innerHTML=""}function L(){c.classList.remove("hidden"),c.classList.add("visible")}function f(){c.classList.add("hidden"),c.classList.remove("visible")}function R(){g.classList.remove("hidden")}function h(){g.classList.add("hidden")}let u="",a=1,i=0;const $=document.querySelector("#search-form"),B=document.querySelector(".load-more");$.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements.searchQuery.value.trim();if(!o){n.warning({message:"Please enter your search query.",position:"topRight"});return}u=o,a=1,q(),h();try{L();const e=await m(u,a);if(i=e.totalHits,e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}n.success({message:`We found ${i} images.`,position:"topRight"}),p(e.hits),i>15&&R()}catch{n.error({message:"Something gone wrong. Please try again later!",position:"topRight"})}finally{f()}});B.addEventListener("click",async()=>{a+=1;try{L();const r=await m(u,a);p(r.hits),M();const o=Math.ceil(i/15);a>=o&&(h(),n.info({message:"Sorry, you have reached the end of the search results.",position:"topRight"}))}catch{n.error({message:"Could not load more images. Please try again.",position:"topRight"})}finally{f()}});function M(){const r=document.querySelector(".gallery li");if(r){const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}h();f();
//# sourceMappingURL=index.js.map
